# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yeahoon Kwon
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: #"/bay" # the subpath of the site
url: "https://deepstroy.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: / # <-- index.md
    #- name: Blog # <-- blog.md
    #- name: Whatever123 # <-- whatever.md

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: dataofyou@snu.ac.kr
      link: mailto:dataofyou@snu.ac.kr
  follow:
    #- name: Twitter
    #  link: http://twitter.com/YourTwitterUsername
    #  username: "@YourTwitterUsername"
    #- name: Facebook
    #  link: http://facebook.com/YourFacebookUsername
    #- name: LinkedIn
    #  link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/Deepstroy/resume
    #- name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- name: RSS
    #  link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
